import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <h1>My Next.js App</h1>
          <p>Welcome to your new Next.js application.</p>
        </header>
        {children}
        <footer>
          <p>&copy; {new Date().getFullYear()} My Next.js App</p>
        </footer>
      </body>
    </html>
  );
}
